### ISSUE TITLE
Attributes without values don't work together with linebreaks

### ISSUE THREAD

**Issue by janv** [netzpirat/haml-coffee#66]
This works:

```
%foo(bar baz)
```

```
<foo bar baz></foo>
```

This also works:

```
%foo(bar=""
     baz="")
```

```
<foo bar='' baz=''></foo>
```

This, however, doesn't:

```
%foo(bar
     baz="")
```

```
  #{ red }[haml coffee] CoffeeScript compilation error:#{ reset } SyntaxError: unexpected STRING
SyntaxError: unexpected STRING
  at Object.exports.throwSyntaxError (/Users/jan/development/haml-coffee/node_modules/coffee-script/lib/coffee-script/helpers.js:209:13)
  at Object.parser.yy.parseError (/Users/jan/development/haml-coffee/node_modules/coffee-script/lib/coffee-script/coffee-script.js:245:20)
  at Object.parse (/Users/jan/development/haml-coffee/node_modules/coffee-script/lib/coffee-script/parser.js:535:22)
  at Object.exports.compile.compile [as compile] (/Users/jan/development/haml-coffee/node_modules/coffee-script/lib/coffee-script/coffee-script.js:36:25)
  at Function.module.exports.CoffeeMaker.compile (/Users/jan/development/haml-coffee/src/cli/coffee-maker.coffee:96:31)
  at ReadStream.exports.run (/Users/jan/development/haml-coffee/src/cli/command.coffee:198:49)
  at ReadStream.EventEmitter.emit (events.js:93:17)
  at TTY.onread (net.js:417:51)
```

**Comment by gottfrois** [comment]
+1 having the exact same issue
